### ISSUE TITLE
Fix project persistency implementation

### ISSUE THREAD

**Issue by suoto** [suoto/hdlcc#4]
Using Pickle to dump/load project objects to a file causes issues when the object is dumped in a Python shell and loaded from another shell that doesn't have access to the objects the original shell had.

For example, building a project within Vim then trying to build it via command line gives the following exception

    Traceback (most recent call last):
      File "/home/asouto/bin/runner.py", line 213, in <module>
        main(runner_args)
      File "/home/asouto/bin/runner.py", line 161, in main
        project.readConfigFile()
      File "/home/asouto/utils/vim/vim/bundle/vim-hdl/python/vimhdl/project_builder.py", line 79, in readConfigFile
        obj = pickle.load(open(cache_fname, 'r'))
      File "/home/asouto/utils/vim/vim/bundle/vim-hdl/python/vimhdl/vim_client.py", line 25, in <module>
        import vim
    ImportError: No module named vim

**Comment by suoto** [comment]
Pickle-like serializers dump whole environment definition and expect the environment to remain somewhat the same.

This approach will be replaced by using JSON to cache only the required attributes. A good side effect is that since class definitions won't be cached, reusing the same cache with different hdlcc versions should be easier.

**Comment by suoto** [comment]
Results using JSON seem OK, need more throughout testing.

**Comment by suoto** [comment]
Fixing this issue should fix issue #2 as well.
